// POST /api/memos/save — persist a generated Strategy Memo into memo_versions.
//
// The memo is template-generated by deterministic code (no LLM). The route stores it
// with the full audit chain: which scenario_results rows, market updates and assumption
// versions it was assembled from. Version numbers are assigned server-side
// (max(version)+1 per project) so reruns across sessions never collide with the
// unique (project_id, version) constraint.
//
// Demo phase: an "approved" memo is stored as human_review_status = 'approved_demo' —
// it is never presented as a real sign-off until auth lands.

import { getSupabaseAdmin, supabaseAdminConfigured } from "@/lib/supabase/admin";
import type { MemoVersionRecord } from "@/lib/types";

export async function POST(request: Request) {
  const config = supabaseAdminConfigured();
  if (!config.ok) {
    return Response.json(
      { ok: false, status: "not_configured", error: `Missing environment variables: ${config.missing.join(", ")}` },
      { status: 503 },
    );
  }

  let memo: MemoVersionRecord;
  try {
    memo = (await request.json()) as MemoVersionRecord;
  } catch {
    return Response.json({ ok: false, error: "Invalid JSON body" }, { status: 400 });
  }
  if (!memo?.project_id || !Array.isArray(memo.content) || memo.content.length === 0) {
    return Response.json({ ok: false, error: "project_id and non-empty content are required" }, { status: 400 });
  }

  const supabase = getSupabaseAdmin();

  // Memos can only reference a persisted project (FK). Local-only studies keep memos local.
  const project = await supabase.from("projects").select("id").eq("id", memo.project_id).maybeSingle();
  if (project.error) {
    return Response.json({ ok: false, error: project.error.message }, { status: 500 });
  }
  if (!project.data) {
    return Response.json(
      { ok: false, status: "project_not_persisted", error: `Project ${memo.project_id} is not saved in Supabase — memo kept local.` },
      { status: 409 },
    );
  }

  // Server-side version: continue from whatever is already stored for this project.
  const latest = await supabase
    .from("memo_versions")
    .select("version")
    .eq("project_id", memo.project_id)
    .order("version", { ascending: false })
    .limit(1)
    .maybeSingle();
  if (latest.error) {
    return Response.json({ ok: false, error: latest.error.message }, { status: 500 });
  }
  const version = (latest.data?.version ?? 0) + 1;

  const approved = memo.human_review_status === "approved";
  const base = {
    id: memo.id,
    project_id: memo.project_id,
    version,
    memo_type: memo.memo_type ?? "cfo",
    content: memo.content, // MemoSection[] as jsonb
    market_update_ids: memo.market_update_ids ?? [],
    assumption_version_ids: memo.assumption_version_ids ?? [],
    assumption_set_version: memo.assumption_set_version,
    approved_by: approved ? "Demo Reviewer" : null,
    approved_at: approved ? (memo.approved_at ?? new Date().toISOString()) : null,
  };

  // Preferred shape (after migration 0004): scenario result links + approved_demo status.
  const full = await supabase.from("memo_versions").insert({
    ...base,
    scenario_result_ids: memo.scenario_result_ids ?? [],
    human_review_status: approved ? "approved_demo" : "pending_review",
  });
  if (!full.error) {
    return Response.json({ ok: true, id: base.id, version, human_review_status: approved ? "approved_demo" : "pending_review" });
  }

  // Legacy retry: migration 0004 not applied yet — save without scenario links,
  // using the original status vocabulary, and say exactly what is missing.
  if (/scenario_result_ids|approved_demo|human_review_status/.test(full.error.message)) {
    const legacy = await supabase.from("memo_versions").insert({
      ...base,
      human_review_status: approved ? "approved" : "pending_review",
    });
    if (!legacy.error) {
      return Response.json({
        ok: true,
        id: base.id,
        version,
        human_review_status: approved ? "approved" : "pending_review",
        warning:
          "Memo saved without scenario_result_ids / approved_demo status — run supabase/APPLY_PENDING.sql to complete migration 0004.",
      });
    }
    return Response.json({ ok: false, error: legacy.error.message }, { status: 500 });
  }

  return Response.json({ ok: false, error: full.error.message }, { status: 500 });
}
